#.travis.yml

language: node_js
node_js:
  - "6.10"

branches:
  only:
    - dev
    - prod
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then ng build --environment=dev; fi
  - if [ "$TRAVIS_BRANCH" == "prod" ]; then ng build --environment=prod; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ng build; fi

#bij productie, production environment van Firebase kiezen (= DZwelg), anders wordt default gebruikt (= DZwelg-dev)
after_success:
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then firebase use default --token $FIREBASE_TOKEN; fi
  - if [ "$TRAVIS_BRANCH" == "prod" ]; then firebase use production --token $FIREBASE_TOKEN; fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then firebase deploy --token $FIREBASE_TOKEN; fi

notifications:
  email:
    on_failure: change
    on_success: change
