#.travis.yml

language: node_js
node_js:
  - "6.10"

branches:
  only:
    - dev
    - prod

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then ng build --target=production --environment=dev; fi
  - if [ "$TRAVIS_BRANCH" = "prod" ]; then ng build --prod; fi

#bij productie, production environment van Firebase kiezen (= DZwelg), anders wordt default gebruikt (= DZwelg-dev)
after_success:
  - if [ "$TRAVIS_BRANCH" = "prod" ]; then firebase use production --token $FIREBASE_TOKEN; fi
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
